spring:
  datasource:
    url: jdbc:postgresql://postgresql-book:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true

  kafka:
    bootstrap-servers: kafka:9093
    topic:
      userCreated: user-created-topic
    consumer:
      group-id: book-service

server:
  port: 8080

api:
  user:
    url: ${USER_API}
