spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
server:
  port: 8080
