spring:
  datasource:
    url: jdbc:postgresql://postgresql-user:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true

  kafka:
    bootstrap-servers: kafka:9093
    consumer:
      group-id: user-service

server:
  port: 8080
